### ISSUE TITLE
ROI for MHL calculation

### ISSUE THREAD

**Issue by nathaliagg** [MPIIComputationalEpigenetics/WSHPackage#5]
Hi Michael!

Thanks for putting this package out. It's super useful!

I'd like to ask two questions: 

1 - What is the `roi.bed` (== MHBs) that you used for the MHL calculation? 

2 - PDR, FDRP and qFDRP are based on single CpG sites, and MHL is based on a region. If my goal is to look at regions, e.g., CpG islands, would it be correct to average the PDR, FDRP and qFDRP values within regions? If not, what would be the best approach?

Thank you!

**Comment by schmic05** [comment]
Hi Nathalia,

I am very happy that you like to package! Don't hesitate to ask any questions, I'll try to answer them as good as possible.

1. The ```roi.bed``` file specifies the regions for which you want to compute MHL and has to be specified by the user. What I typically did was to extract the ROI as the CpGs that I want to compute MHL for (which are also those that I use for FDRP etc. calculation). You can extract this, for instance, from RnBeads.

2. Yes, you are right. In such a setting, aggregating the values over pre-defined regions is reasonable. This is similar to what many people do with single-CpG methylation calls.

I hope that helps,

Michael

**Comment by nathaliagg** [comment]
Thank you for the clarification! I have another question. How did you handle SNPs in BS-seq data? Did you mask them prior to calculating the metrics, or did you exclude them from the CpG `roi.bed`? 

Thanks again,

Nathalia.

**Comment by schmic05** [comment]
Here, RnBeads (https://rnbeads.org) can also come to your help, since the tools can automatically remove SNPs (those annotated in dbSNP). I think it might be useful for you to have a closer look into RnBeads, since I also used it for preprocessing. The default preprocessing of RnBeads typically works quite well, but I would re-specify the coverage filtering (parameters: filtering.coverage.cutoff and filtering.missing.value.quantile).

Hope that helps,

Michael

**Comment by nathaliagg** [comment]
That's handy! I was not familiar with RnBeads (I mainly work in Python), but will definitely check it out! Thanks a lot, Michael!

Nathalia

**Comment by schmic05** [comment]
You are very welcome, don't hesitate to ask any further questions!
